export enum VideoCategoryType {
  "Film & Animation",
  "Autos & Vehicles",
  "Music",
  "Pets & Animals",
  "Sports",
  "Short Movies",
  "Travel & Events",
  "Gaming",
  "Videoblogging",
  "People & Blogs",
  "Comedy",
  "Entertainment",
  "News & Politics",
  "Howto & Style",
  "Education",
  "Science & Technology",
  "Nonprofit & Activism",
  "Movies",
  "Anime/Animation",
  "Action/Adventure",
  "Classics",
  "Documentary",
  "Drama",
  "Family",
  "Foreign",
  "Horror",
  "Sci-Fi/Fantasy",
  "Shorts",
  "Shows",
  "Thriller",
  "Trailers"
}
